apiVersion: v1
kind: Secret
metadata:
  name: event-hub-utils
type: Opaque
stringData:
  EVENTHUB_CONNECTION_STRING: "Endpoint=sb://<eventhubname>.servicebus.windows.net/;SharedAccessKeyName=<keyname>;SharedAccessKey=<accesskey>;EntityPath=<pathname>"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-hub-utils
spec:
  replicas: 1  # Number of replicas (pods) you want to run
  selector:
    matchLabels:
      app: event-hub-utils
  template:
    metadata:
      labels:
        app: event-hub-utils
    spec:
      containers:
      - name: event-hub-utils
        image: rmarcello/event-hub-utils:0.0.1
        ports:
        - containerPort: 8080  # Port inside the container
        envFrom:
          - secretRef:
              name: event-hub-utils
---
apiVersion: v1
kind: Service
metadata:
  name: event-hub-utils
  labels:
    app: event-hub-utils
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: event-hub-utils
  type: ClusterIP